#!/usr/bin/env bash
# Generate CI security scanning pipeline recommendations
# Usage: ci-recommend.sh --stack-json <file> --ci-system <system>
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/lib/common.sh"
source "${SCRIPT_DIR}/lib/tool-registry.sh"

STACK_JSON=""
CI_SYSTEM=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --stack-json)
      STACK_JSON="$2"
      shift 2
      ;;
    --ci-system)
      CI_SYSTEM="$2"
      shift 2
      ;;
    *) shift ;;
  esac
done

if [[ -z "$STACK_JSON" ]] || ! [[ -f "$STACK_JSON" ]]; then
  log_error "Stack JSON required"
  exit 1
fi

# Parse stack
parse_json_array() {
  echo "$1" | tr -d '[]"' | tr ',' '\n' | tr -d ' ' | grep -v '^$'
}

# Read each field on its own line to avoid whitespace-splitting JSON arrays
_stack_fields=$(python3 -c "
import json, sys
d = json.load(open(sys.argv[1]))
print(json.dumps(d.get('languages', [])))
print(str(d.get('docker', False)).lower())
print(json.dumps(d.get('ciSystems', [])))
print(json.dumps(d.get('iacTools', [])))
" "$STACK_JSON" 2>/dev/null || printf '[]\nfalse\n[]\n[]\n')
{
  IFS= read -r languages
  IFS= read -r has_docker
  IFS= read -r ci_systems
  IFS= read -r iac_tools
} <<<"$_stack_fields"

# Auto-detect CI if not specified
if [[ -z "$CI_SYSTEM" ]]; then
  CI_SYSTEM=$(parse_json_array "$ci_systems" | head -1)
fi

if [[ -z "$CI_SYSTEM" ]]; then
  CI_SYSTEM="github-actions"
  log_info "No CI system detected, defaulting to GitHub Actions"
fi

# Determine which tools to include
tools=()
while IFS= read -r lang; do
  [[ -z "$lang" ]] && continue
  while IFS= read -r tool; do
    [[ -z "$tool" ]] && continue
    found=false
    for existing in "${tools[@]+"${tools[@]}"}"; do
      [[ "$existing" == "$tool" ]] && found=true && break
    done
    $found || tools+=("$tool")
  done < <(get_tools_for_stack "$lang" | tr ' ' '\n')
done < <(parse_json_array "$languages")

if [[ "$has_docker" == "true" ]]; then
  for tool in $(get_tools_for_stack "docker"); do
    found=false
    for e in "${tools[@]+"${tools[@]}"}"; do [[ "$e" == "$tool" ]] && found=true && break; done
    $found || tools+=("$tool")
  done
fi
if echo "$iac_tools" | grep -q '[a-z]'; then
  for tool in $(get_tools_for_stack "iac"); do
    found=false
    for e in "${tools[@]+"${tools[@]}"}"; do [[ "$e" == "$tool" ]] && found=true && break; done
    $found || tools+=("$tool")
  done
fi

# ── Generate CI config ────────────────────────────────────────────────
case "$CI_SYSTEM" in
  github-actions)
    cat <<'GHEOF'
# ============================================================
# GitHub Actions: Security Scanning Pipeline
# Generated by code-guardian
# Add this to .github/workflows/security.yml
# ============================================================

name: Security Scan

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]
  schedule:
    - cron: '0 6 * * 1'  # Weekly Monday 6am

permissions:
  contents: read
  security-events: write

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      # Secret detection
      - name: Gitleaks (secret detection)
        uses: gitleaks/gitleaks-action@ff98106e4c7b2bc287b24eaf42907196329070c7 # v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Multi-language SAST
      - name: Semgrep (SAST)
        uses: semgrep/semgrep-action@713efdd345f3035192eaa63f56867b88e63e4e5d # v1
        with:
          config: auto

GHEOF

    # Add language-specific steps
    for tool in "${tools[@]}"; do
      case "$tool" in
        trivy)
          cat <<'TRIVYEOF'
      # Vulnerability scanning
      - name: Trivy (vulnerability scan)
        uses: aquasecurity/trivy-action@e368e328979b113139d6f9068e03accaed98a518 # 0.34.1
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
      - name: Upload Trivy results
        uses: github/codeql-action/upload-sarif@ae9ef3a1d2e3413523c3741725c30064970cc0d4 # v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'

TRIVYEOF
          ;;
        hadolint)
          cat <<'HADOEOF'
      # Dockerfile linting
      - name: Hadolint (Dockerfile lint)
        uses: hadolint/hadolint-action@54c9adbab1582c2ef04b2016b760714a4bfde3cf # v3.1.0
        with:
          dockerfile: Dockerfile

HADOEOF
          ;;
        checkov)
          cat <<'CHECKOVEOF'
      # IaC scanning
      - name: Checkov (IaC security)
        uses: bridgecrewio/checkov-action@4b38516b47b2df46475d84383f9aa2c8ef912aae # v12
        with:
          directory: .
          quiet: true
          soft_fail: true

CHECKOVEOF
          ;;
        npm-audit)
          cat <<'NPMEOF'
      # Dependency audit
      - name: npm audit
        run: npm audit --audit-level=high
        continue-on-error: true

NPMEOF
          ;;
        pip-audit)
          cat <<'PIPEOF'
      # Python dependency audit
      - name: pip-audit
        run: |
          pip install pip-audit
          pip-audit -r requirements.txt
        continue-on-error: true

PIPEOF
          ;;
        bandit)
          cat <<'BANDITEOF'
      # Python SAST
      - name: Bandit (Python SAST)
        run: |
          pip install bandit
          bandit -r . -f json -o bandit-results.json || true
        continue-on-error: true

BANDITEOF
          ;;
        gosec)
          cat <<'GOSECEOF'
      # Go SAST
      - name: gosec (Go SAST)
        uses: securego/gosec@271492bcd930ef72dfb9d00e5bb9544b3b407fb5 # v2.24.0
        with:
          args: ./...

GOSECEOF
          ;;
        osv-scanner)
          cat <<'OSVEOF'
      # Universal dependency audit
      - name: OSV-Scanner (dependency vulnerabilities)
        uses: google/osv-scanner-action/osv-scanner@c5996e0193a3df57d695c1b8a1dec2a4c62e8730 # v2.3.3
        with:
          scan-args: -r .
        continue-on-error: true

OSVEOF
          ;;
        trufflehog)
          cat <<'THEOF'
      # Deep secret detection
      - name: TruffleHog (secret detection)
        uses: trufflesecurity/trufflehog@041f07e9df901a1038a528e5525b0226d04dd5ea # v3.93.6
        with:
          extra_args: --only-verified

THEOF
          ;;
        phpstan)
          cat <<'PHPSTANEOF'
      # PHP static analysis
      - name: PHPStan (PHP SAST)
        run: |
          composer global require phpstan/phpstan
          phpstan analyse --error-format=json --no-progress --level=5 . || true
        continue-on-error: true

PHPSTANEOF
          ;;
        bearer)
          cat <<'BEAREREOF'
      # Data-flow SAST
      - name: Bearer (data-flow SAST)
        uses: bearer/bearer-action@828eeb928ce2f4a7ca5ed57fb8b59508cb8c79bc
        with:
          format: json
          output: bearer-results.json
        continue-on-error: true

BEAREREOF
          ;;
        grype)
          cat <<'GRYPEEOF'
      # Vulnerability scanning
      - name: Grype (vulnerability scan)
        uses: anchore/scan-action@1638637db639e0ade3258b51db49a9a137574c3e
        with:
          path: '.'
          fail-build: false
          output-format: json

GRYPEEOF
          ;;
        kics)
          cat <<'KICSEOF'
      # IaC scanning (KICS)
      - name: KICS (IaC security)
        uses: checkmarx/kics-github-action@05aa5eb70eede1355220f4ca5238d96b397e30a6
        with:
          path: '.'
          output_formats: json
          enable_comments: false
        continue-on-error: true

KICSEOF
          ;;
        composer-audit)
          cat <<'COMPOSEREOF'
      # PHP dependency audit
      - name: Composer audit
        run: composer audit --format=json || true
        continue-on-error: true

COMPOSEREOF
          ;;
        dotnet-audit)
          cat <<'DOTNETEOF'
      # .NET dependency audit
      - name: dotnet audit
        run: dotnet list package --vulnerable --format json || true
        continue-on-error: true

DOTNETEOF
          ;;
        spotbugs)
          cat <<'SPOTBUGSEOF'
      # Java bytecode SAST
      - name: SpotBugs (Java SAST)
        run: |
          spotbugs -textui -xml -effort:max -low . || true
        continue-on-error: true

SPOTBUGSEOF
          ;;
        cppcheck)
          cat <<'CPPCHECKEOF'
      # C/C++ static analysis
      - name: cppcheck (C/C++ SAST)
        run: |
          sudo apt-get install -y cppcheck
          cppcheck --xml --enable=warning,portability --error-exitcode=0 . 2> cppcheck-results.xml || true
        continue-on-error: true

CPPCHECKEOF
          ;;
        swiftlint)
          cat <<'SWIFTLINTEOF'
      # Swift linting
      - name: SwiftLint
        run: |
          brew install swiftlint
          swiftlint lint --reporter json --quiet > swiftlint-results.json || true
        continue-on-error: true

SWIFTLINTEOF
          ;;
        sobelow)
          cat <<'SOBELOWEOF'
      # Elixir security scanning
      - name: Sobelow (Elixir SAST)
        run: |
          mix archive.install hex sobelow --force
          mix sobelow --format json --quiet > sobelow-results.json || true
        continue-on-error: true

SOBELOWEOF
          ;;
        dart-analyze)
          cat <<'DARTEOF'
      # Dart/Flutter static analysis
      - name: dart analyze
        run: dart analyze --format=json . > dart-analyze-results.json || true
        continue-on-error: true

DARTEOF
          ;;
      esac
    done
    ;;

  gitlab-ci)
    cat <<'GLEOF'
# ============================================================
# GitLab CI: Security Scanning Pipeline
# Generated by code-guardian
# Add this to .gitlab-ci.yml (or include it)
# ============================================================

stages:
  - security

variables:
  SECURE_LOG_LEVEL: "warn"

gitleaks:
  stage: security
  image: zricethezav/gitleaks:v8.30.0@sha256:691af3c7c5a48b16f187ce3446d5f194838f91238f27270ed36eef6359a574d9
  script:
    - gitleaks detect --source . --report-format json --report-path gitleaks-report.json --no-banner
  artifacts:
    reports:
      secret_detection: gitleaks-report.json
    when: always
  allow_failure: true

semgrep:
  stage: security
  image: semgrep/semgrep:1.154.0@sha256:9fb6f44dc162b1e0aada85f072a95141844c61e3bfcedf40b8a46fecf208e986
  script:
    - semgrep --config auto --json --output semgrep-results.json .
  artifacts:
    paths:
      - semgrep-results.json
    when: always
  allow_failure: true

GLEOF

    for tool in "${tools[@]}"; do
      case "$tool" in
        trivy)
          cat <<'GLTRIVYEOF'
trivy:
  stage: security
  image: aquasec/trivy:0.69.3@sha256:bcc376de8d77cfe086a917230e818dc9f8528e3c852f7b1aff648949b6258d1c
  script:
    - trivy fs --format json --output trivy-results.json --severity CRITICAL,HIGH .
  artifacts:
    paths:
      - trivy-results.json
    when: always
  allow_failure: true

GLTRIVYEOF
          ;;
        checkov)
          cat <<'GLCHECKOVEOF'
checkov:
  stage: security
  image: bridgecrew/checkov:3.2.507@sha256:2bcc40c76b433ec0f9cf7fd23e7c2495c0a9a270b3cc7fe891249c207d4d1427
  script:
    - checkov -d . --output json --quiet > checkov-results.json || true
  artifacts:
    paths:
      - checkov-results.json
    when: always
  allow_failure: true

GLCHECKOVEOF
          ;;
        osv-scanner)
          cat <<'GLOSVEOF'
osv-scanner:
  stage: security
  image: ghcr.io/google/osv-scanner:v2.3.3@sha256:bf249317dcf838cf9e47f370cfd4dd4178d875bba14e3ce74d299c5bf1b129a1
  script:
    - osv-scanner --format json -r . > osv-results.json || true
  artifacts:
    paths:
      - osv-results.json
    when: always
  allow_failure: true

GLOSVEOF
          ;;
        trufflehog)
          cat <<'GLTHEOF'
trufflehog:
  stage: security
  image: trufflesecurity/trufflehog:3.93.7@sha256:2b23135478a0b842bcab4b5805a4f9ac48e72a2e01f1b1a866b964c715aa4645
  script:
    - trufflehog filesystem --json --no-update . > trufflehog-results.json || true
  artifacts:
    paths:
      - trufflehog-results.json
    when: always
  allow_failure: true

GLTHEOF
          ;;
        phpstan)
          cat <<'GLPHPSTANEOF'
phpstan:
  stage: security
  image: ghcr.io/phpstan/phpstan:2.1.40@sha256:c1b03e01f711d871760f02f0142a53e5c8d6c5387c28f53cdc22c072d4f10fdd
  script:
    - phpstan analyse --error-format=json --no-progress --level=5 . > phpstan-results.json || true
  artifacts:
    paths:
      - phpstan-results.json
    when: always
  allow_failure: true

GLPHPSTANEOF
          ;;
        bearer)
          cat <<'GLBEAREREOF'
bearer:
  stage: security
  image: bearer/bearer:v1.51.1@sha256:b7be1db4e02cc6f57f5da9e07115e9f89385597ac9dc3a6fc9b4977e4ad7f160
  script:
    - bearer scan . --format json --quiet > bearer-results.json || true
  artifacts:
    paths:
      - bearer-results.json
    when: always
  allow_failure: true

GLBEAREREOF
          ;;
        grype)
          cat <<'GLGRYPEEOF'
grype:
  stage: security
  image: anchore/grype:v0.109.0@sha256:fc348b3af991774d5ff1bb347c20398797660937eac0398b428f7475f32ff064
  script:
    - grype dir:. --output json --quiet > grype-results.json || true
  artifacts:
    paths:
      - grype-results.json
    when: always
  allow_failure: true

GLGRYPEEOF
          ;;
        kics)
          cat <<'GLKICSEOF'
kics:
  stage: security
  image: checkmarx/kics:v2.1.20@sha256:3e5a268eb8adda2e5a483c9359ddfc4cd520ab856a7076dc0b1d8784a37e2602
  script:
    - kics scan -p . --output-path /tmp/kics --report-formats json --no-progress || true
    - cp /tmp/kics/results.json kics-results.json || true
  artifacts:
    paths:
      - kics-results.json
    when: always
  allow_failure: true

GLKICSEOF
          ;;
        composer-audit)
          cat <<'GLCOMPOSEREOF'
composer-audit:
  stage: security
  image: composer:latest@sha256:f0809732b2188154b3faa8e44ab900595acb0b09cd0aa6c34e798efe4ebc9021
  script:
    - composer audit --format=json > composer-audit-results.json || true
  artifacts:
    paths:
      - composer-audit-results.json
    when: always
  allow_failure: true

GLCOMPOSEREOF
          ;;
        dotnet-audit)
          cat <<'GLDOTNETEOF'
dotnet-audit:
  stage: security
  image: mcr.microsoft.com/dotnet/sdk:8.0@sha256:bfb6ed602caa605141700aea7dc7d42574b74b704368e67d683c71a002123808
  script:
    - dotnet list package --vulnerable --format json > dotnet-audit-results.json || true
  artifacts:
    paths:
      - dotnet-audit-results.json
    when: always
  allow_failure: true

GLDOTNETEOF
          ;;
        spotbugs)
          cat <<'GLSPOTBUGSEOF'
spotbugs:
  stage: security
  image: eclipse-temurin:21-jdk@sha256:c880d7bdbcab3bb1e82159d5781760832e94b72b65dfa1835b4c23b241232b45
  before_script:
    - apt-get update && apt-get install -y spotbugs
  script:
    - spotbugs -textui -xml -effort:max -low . > spotbugs-results.xml || true
  artifacts:
    paths:
      - spotbugs-results.xml
    when: always
  allow_failure: true

GLSPOTBUGSEOF
          ;;
        cppcheck)
          cat <<'GLCPPCHECKEOF'
cppcheck:
  stage: security
  image: facthunder/cppcheck:2.16.0
  script:
    - cppcheck --xml --enable=warning,portability --error-exitcode=0 . 2> cppcheck-results.xml || true
  artifacts:
    paths:
      - cppcheck-results.xml
    when: always
  allow_failure: true

GLCPPCHECKEOF
          ;;
        swiftlint)
          cat <<'GLSWIFTLINTEOF'
swiftlint:
  stage: security
  image: ghcr.io/realm/swiftlint:0.63.2@sha256:8db376ff8a26e56fa506b56b8c70ea9c5583dc52d5746ce23b6c2c4d4ee00e31
  script:
    - swiftlint lint --reporter json --quiet > swiftlint-results.json || true
  artifacts:
    paths:
      - swiftlint-results.json
    when: always
  allow_failure: true

GLSWIFTLINTEOF
          ;;
        sobelow)
          cat <<'GLSOBELOWEOF'
sobelow:
  stage: security
  image: elixir:latest@sha256:35f607850c21611039d994219811922207d611ce46bfd108311a92d0a849bc7f
  script:
    - mix local.hex --force
    - mix archive.install hex sobelow --force
    - mix sobelow --format json --quiet > sobelow-results.json || true
  artifacts:
    paths:
      - sobelow-results.json
    when: always
  allow_failure: true

GLSOBELOWEOF
          ;;
        dart-analyze)
          cat <<'GLDARTEOF'
dart-analyze:
  stage: security
  image: dart:stable@sha256:e3ea62cbe54470e5cc4c31cbc85693aa9b0b01723521baf0be634ea3597e1f5d
  script:
    - dart analyze --format=json . > dart-analyze-results.json || true
  artifacts:
    paths:
      - dart-analyze-results.json
    when: always
  allow_failure: true

GLDARTEOF
          ;;
      esac
    done
    ;;

  *)
    cat <<GENERICEOF
# ============================================================
# Generic CI: Security Scanning Pipeline
# Generated by code-guardian
# Adapt to your CI system ($CI_SYSTEM)
# ============================================================

# Step 1: Secret detection
gitleaks detect --source . --report-format json --report-path gitleaks-report.json

# Step 2: SAST
semgrep --config auto --json --output semgrep-results.json .

# Step 3: Vulnerability scanning
trivy fs --format json --output trivy-results.json --severity CRITICAL,HIGH .

GENERICEOF

    for tool in "${tools[@]}"; do
      case "$tool" in
        hadolint)
          echo "# Dockerfile linting"
          echo "hadolint Dockerfile"
          echo ""
          ;;
        checkov)
          echo "# IaC scanning"
          echo "checkov -d . --output json --quiet"
          echo ""
          ;;
        npm-audit)
          echo "# JS dependency audit"
          echo "npm audit --audit-level=high"
          echo ""
          ;;
        pip-audit)
          echo "# Python dependency audit"
          echo "pip-audit -r requirements.txt"
          echo ""
          ;;
        bandit)
          echo "# Python SAST"
          echo "bandit -r . -f json"
          echo ""
          ;;
        gosec)
          echo "# Go SAST"
          echo "gosec -fmt=json ./..."
          echo ""
          ;;
        osv-scanner)
          echo "# Universal dependency audit"
          echo "osv-scanner --format json -r ."
          echo ""
          ;;
        trufflehog)
          echo "# Deep secret detection"
          echo "trufflehog filesystem --json --no-update ."
          echo ""
          ;;
        phpstan)
          echo "# PHP static analysis"
          echo "phpstan analyse --error-format=json --no-progress --level=5 ."
          echo ""
          ;;
        bearer)
          echo "# Data-flow SAST"
          echo "bearer scan . --format json --quiet"
          echo ""
          ;;
        grype)
          echo "# Vulnerability scanning (Grype)"
          echo "grype dir:. --output json --quiet"
          echo ""
          ;;
        kics)
          echo "# IaC scanning (KICS)"
          echo "kics scan -p . --output-path /tmp/kics --report-formats json --no-progress"
          echo ""
          ;;
        composer-audit)
          echo "# PHP dependency audit"
          echo "composer audit --format=json"
          echo ""
          ;;
        dotnet-audit)
          echo "# .NET dependency audit"
          echo "dotnet list package --vulnerable --format json"
          echo ""
          ;;
        spotbugs)
          echo "# Java bytecode SAST"
          echo "spotbugs -textui -xml -effort:max -low ."
          echo ""
          ;;
        cppcheck)
          echo "# C/C++ static analysis"
          echo "cppcheck --xml --enable=warning,portability --error-exitcode=0 ."
          echo ""
          ;;
        swiftlint)
          echo "# Swift linting"
          echo "swiftlint lint --reporter json --quiet"
          echo ""
          ;;
        sobelow)
          echo "# Elixir security scanning"
          echo "mix sobelow --format json --quiet"
          echo ""
          ;;
        dart-analyze)
          echo "# Dart/Flutter static analysis"
          echo "dart analyze --format=json ."
          echo ""
          ;;
      esac
    done
    ;;
esac
