#!/usr/bin/env bash
# Generate CI security scanning pipeline recommendations
# Usage: ci-recommend.sh --stack-json <file> --ci-system <system>
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/lib/common.sh"
source "${SCRIPT_DIR}/lib/tool-registry.sh"

STACK_JSON=""
CI_SYSTEM=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --stack-json) STACK_JSON="$2"; shift 2 ;;
    --ci-system) CI_SYSTEM="$2"; shift 2 ;;
    *) shift ;;
  esac
done

if [[ -z "$STACK_JSON" ]] || ! [[ -f "$STACK_JSON" ]]; then
  log_error "Stack JSON required"
  exit 1
fi

# Parse stack
parse_json_array() {
  echo "$1" | tr -d '[]"' | tr ',' '\n' | tr -d ' ' | grep -v '^$'
}

# Read each field on its own line to avoid whitespace-splitting JSON arrays
_stack_fields=$(python3 -c "
import json, sys
d = json.load(open(sys.argv[1]))
print(json.dumps(d.get('languages', [])))
print(str(d.get('docker', False)).lower())
print(json.dumps(d.get('ciSystems', [])))
print(json.dumps(d.get('iacTools', [])))
" "$STACK_JSON" 2>/dev/null || printf '[]\nfalse\n[]\n[]\n')
{ IFS= read -r languages; IFS= read -r has_docker; IFS= read -r ci_systems; IFS= read -r iac_tools; } <<< "$_stack_fields"

# Auto-detect CI if not specified
if [[ -z "$CI_SYSTEM" ]]; then
  CI_SYSTEM=$(parse_json_array "$ci_systems" | head -1)
fi

if [[ -z "$CI_SYSTEM" ]]; then
  CI_SYSTEM="github-actions"
  log_info "No CI system detected, defaulting to GitHub Actions"
fi

# Determine which tools to include
tools=()
while IFS= read -r lang; do
  [[ -z "$lang" ]] && continue
  while IFS= read -r tool; do
    [[ -z "$tool" ]] && continue
    found=false
    for existing in "${tools[@]+"${tools[@]}"}"; do
      [[ "$existing" == "$tool" ]] && found=true && break
    done
    $found || tools+=("$tool")
  done < <(get_tools_for_stack "$lang" | tr ' ' '\n')
done < <(parse_json_array "$languages")

if [[ "$has_docker" == "true" ]]; then
  for tool in $(get_tools_for_stack "docker"); do
    found=false; for e in "${tools[@]+"${tools[@]}"}"; do [[ "$e" == "$tool" ]] && found=true && break; done
    $found || tools+=("$tool")
  done
fi
if echo "$iac_tools" | grep -q '[a-z]'; then
  for tool in $(get_tools_for_stack "iac"); do
    found=false; for e in "${tools[@]+"${tools[@]}"}"; do [[ "$e" == "$tool" ]] && found=true && break; done
    $found || tools+=("$tool")
  done
fi

# ── Generate CI config ────────────────────────────────────────────────
case "$CI_SYSTEM" in
  github-actions)
    cat <<'GHEOF'
# ============================================================
# GitHub Actions: Security Scanning Pipeline
# Generated by code-guardian
# Add this to .github/workflows/security.yml
# ============================================================

name: Security Scan

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]
  schedule:
    - cron: '0 6 * * 1'  # Weekly Monday 6am

permissions:
  contents: read
  security-events: write

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      # Secret detection
      - name: Gitleaks (secret detection)
        uses: gitleaks/gitleaks-action@ff98106e4c7b2bc287b24eaf42907196329070c7 # v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Multi-language SAST
      - name: Semgrep (SAST)
        uses: semgrep/semgrep-action@713efdd345f3035192eaa63f56867b88e63e4e5d # v1
        with:
          config: auto

GHEOF

    # Add language-specific steps
    for tool in "${tools[@]}"; do
      case "$tool" in
        trivy)
          cat <<'TRIVYEOF'
      # Vulnerability scanning
      - name: Trivy (vulnerability scan)
        uses: aquasecurity/trivy-action@e368e328979b113139d6f9068e03accaed98a518 # 0.34.1
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
      - name: Upload Trivy results
        uses: github/codeql-action/upload-sarif@45580472a5bb82c4681c4ac726cfdb60060c2ee1 # v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'

TRIVYEOF
          ;;
        hadolint)
          cat <<'HADOEOF'
      # Dockerfile linting
      - name: Hadolint (Dockerfile lint)
        uses: hadolint/hadolint-action@54c9adbab1582c2ef04b2016b760714a4bfde3cf # v3.1.0
        with:
          dockerfile: Dockerfile

HADOEOF
          ;;
        checkov)
          cat <<'CHECKOVEOF'
      # IaC scanning
      - name: Checkov (IaC security)
        uses: bridgecrewio/checkov-action@f99709f8ccc3496220c987b7d8729653237c23dc # v12
        with:
          directory: .
          quiet: true
          soft_fail: true

CHECKOVEOF
          ;;
        npm-audit)
          cat <<'NPMEOF'
      # Dependency audit
      - name: npm audit
        run: npm audit --audit-level=high
        continue-on-error: true

NPMEOF
          ;;
        pip-audit)
          cat <<'PIPEOF'
      # Python dependency audit
      - name: pip-audit
        run: |
          pip install pip-audit
          pip-audit -r requirements.txt
        continue-on-error: true

PIPEOF
          ;;
        bandit)
          cat <<'BANDITEOF'
      # Python SAST
      - name: Bandit (Python SAST)
        run: |
          pip install bandit
          bandit -r . -f json -o bandit-results.json || true
        continue-on-error: true

BANDITEOF
          ;;
        gosec)
          cat <<'GOSECEOF'
      # Go SAST
      - name: gosec (Go SAST)
        uses: securego/gosec@271492bcd930ef72dfb9d00e5bb9544b3b407fb5 # v2.24.0
        with:
          args: ./...

GOSECEOF
          ;;
        osv-scanner)
          cat <<'OSVEOF'
      # Universal dependency audit
      - name: OSV-Scanner (dependency vulnerabilities)
        uses: google/osv-scanner-action/osv-scanner@c5996e0193a3df57d695c1b8a1dec2a4c62e8730 # v2.3.3
        with:
          scan-args: -r .
        continue-on-error: true

OSVEOF
          ;;
        trufflehog)
          cat <<'THEOF'
      # Deep secret detection
      - name: TruffleHog (secret detection)
        uses: trufflesecurity/trufflehog@041f07e9df901a1038a528e5525b0226d04dd5ea # v3.93.6
        with:
          extra_args: --only-verified

THEOF
          ;;
        phpstan)
          cat <<'PHPSTANEOF'
      # PHP static analysis
      - name: PHPStan (PHP SAST)
        run: |
          composer global require phpstan/phpstan
          phpstan analyse --error-format=json --no-progress --level=5 . || true
        continue-on-error: true

PHPSTANEOF
          ;;
      esac
    done
    ;;

  gitlab-ci)
    cat <<'GLEOF'
# ============================================================
# GitLab CI: Security Scanning Pipeline
# Generated by code-guardian
# Add this to .gitlab-ci.yml (or include it)
# ============================================================

stages:
  - security

variables:
  SECURE_LOG_LEVEL: "warn"

gitleaks:
  stage: security
  image: zricethezav/gitleaks:v8.30.0
  script:
    - gitleaks detect --source . --report-format json --report-path gitleaks-report.json --no-banner
  artifacts:
    reports:
      secret_detection: gitleaks-report.json
    when: always
  allow_failure: true

semgrep:
  stage: security
  image: semgrep/semgrep:1.153.0
  script:
    - semgrep --config auto --json --output semgrep-results.json .
  artifacts:
    paths:
      - semgrep-results.json
    when: always
  allow_failure: true

GLEOF

    for tool in "${tools[@]}"; do
      case "$tool" in
        trivy)
          cat <<'GLTRIVYEOF'
trivy:
  stage: security
  image: aquasec/trivy:0.69.1
  script:
    - trivy fs --format json --output trivy-results.json --severity CRITICAL,HIGH .
  artifacts:
    paths:
      - trivy-results.json
    when: always
  allow_failure: true

GLTRIVYEOF
          ;;
        checkov)
          cat <<'GLCHECKOVEOF'
checkov:
  stage: security
  image: bridgecrew/checkov:3.2.506
  script:
    - checkov -d . --output json --quiet > checkov-results.json || true
  artifacts:
    paths:
      - checkov-results.json
    when: always
  allow_failure: true

GLCHECKOVEOF
          ;;
        osv-scanner)
          cat <<'GLOSVEOF'
osv-scanner:
  stage: security
  image: ghcr.io/google/osv-scanner:v2.3.3
  script:
    - osv-scanner --format json -r . > osv-results.json || true
  artifacts:
    paths:
      - osv-results.json
    when: always
  allow_failure: true

GLOSVEOF
          ;;
        trufflehog)
          cat <<'GLTHEOF'
trufflehog:
  stage: security
  image: trufflesecurity/trufflehog:3.93.6
  script:
    - trufflehog filesystem --json --no-update . > trufflehog-results.json || true
  artifacts:
    paths:
      - trufflehog-results.json
    when: always
  allow_failure: true

GLTHEOF
          ;;
        phpstan)
          cat <<'GLPHPSTANEOF'
phpstan:
  stage: security
  image: ghcr.io/phpstan/phpstan:2.1
  script:
    - phpstan analyse --error-format=json --no-progress --level=5 . > phpstan-results.json || true
  artifacts:
    paths:
      - phpstan-results.json
    when: always
  allow_failure: true

GLPHPSTANEOF
          ;;
      esac
    done
    ;;

  *)
    cat <<GENERICEOF
# ============================================================
# Generic CI: Security Scanning Pipeline
# Generated by code-guardian
# Adapt to your CI system ($CI_SYSTEM)
# ============================================================

# Step 1: Secret detection
gitleaks detect --source . --report-format json --report-path gitleaks-report.json

# Step 2: SAST
semgrep --config auto --json --output semgrep-results.json .

# Step 3: Vulnerability scanning
trivy fs --format json --output trivy-results.json --severity CRITICAL,HIGH .

GENERICEOF

    for tool in "${tools[@]}"; do
      case "$tool" in
        hadolint) echo "# Dockerfile linting"; echo "hadolint Dockerfile"; echo "" ;;
        checkov) echo "# IaC scanning"; echo "checkov -d . --output json --quiet"; echo "" ;;
        npm-audit) echo "# JS dependency audit"; echo "npm audit --audit-level=high"; echo "" ;;
        pip-audit) echo "# Python dependency audit"; echo "pip-audit -r requirements.txt"; echo "" ;;
        bandit) echo "# Python SAST"; echo "bandit -r . -f json"; echo "" ;;
        gosec) echo "# Go SAST"; echo "gosec -fmt=json ./..."; echo "" ;;
        osv-scanner) echo "# Universal dependency audit"; echo "osv-scanner --format json -r ."; echo "" ;;
        trufflehog) echo "# Deep secret detection"; echo "trufflehog filesystem --json --no-update ."; echo "" ;;
        phpstan) echo "# PHP static analysis"; echo "phpstan analyse --error-format=json --no-progress --level=5 ."; echo "" ;;
      esac
    done
    ;;
esac
